-- Add migration script here
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_app_id;
ALTER TABLE apps ALTER COLUMN id SET DATA TYPE VARCHAR(255);
ALTER TABLE users ALTER COLUMN id SET DATA TYPE VARCHAR(255);
ALTER TABLE users ALTER COLUMN app_id SET DATA TYPE VARCHAR(255);
ALTER TABLE users ADD CONSTRAINT fk_users_app_id FOREIGN KEY (app_id) REFERENCES apps(id) ON DELETE CASCADE;